backend/modules/common/controllers/AttachmentCateController.php
<?php

namespace backend\modules\common\controllers;

use Yii;
use common\models\common\AttachmentCate;
use backend\controllers\BaseController;
use common\traits\MerchantCurd;
use yii\data\ActiveDataProvider;

/**
 * Class AttachmentCateController
 * @package backend\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class AttachmentCateController extends BaseController
{
    use MerchantCurd;

    /**
     * @var AttachmentCate
     */
    public $modelClass = AttachmentCate::class;

    /**
     * Lists all Tree models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => $this->modelClass::find()
                ->orderBy('sort asc, created_at asc'),
            'pagination' => false
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * 编辑/创建
     *
     * @return mixed|string|\yii\web\Response
     * @throws \yii\base\ExitException
     */
    public function actionAjaxEdit()
    {
        $request = Yii::$app->request;
        $id = $request->get('id', '');
        $model = $this->findModel($id);
        $model->pid = $request->get('pid', null) ?? $model->pid; // 父id

        // ajax 校验
        $this->activeFormValidate($model);
        if ($model->load($request->post())) {
            return $model->save()
                ? $this->redirect(['index'])
                : $this->message($this->getError($model), $this->redirect(['index']), 'error');
        }

        return $this->renderAjax('ajax-edit', [
            'model' => $model,
        ]);
    }
}

backend/modules/common/controllers/AttachmentController.php
<?php

namespace backend\modules\common\controllers;

use Yii;
use common\traits\MerchantCurd;
use common\models\base\SearchModel;
use common\models\common\Attachment;
use common\enums\StatusEnum;
use backend\controllers\BaseController;

/**
 * Class AttachmentController
 * @package backend\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class AttachmentController extends BaseController
{
    use MerchantCurd;

    /**
     * @var Attachment
     */
    public $modelClass = Attachment::class;

    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $searchModel = new SearchModel([
            'model' => $this->modelClass,
            'scenario' => 'default',
            'partialMatchAttributes' => ['title'], // 模糊查询
            'defaultOrder' => [
                'id' => SORT_DESC,
            ],
            'pageSize' => $this->pageSize,
        ]);

        $dataProvider = $searchModel
            ->search(Yii::$app->request->queryParams);
        $dataProvider->query
            ->andWhere(['>=', 'status', StatusEnum::DISABLED])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()]);

        return $this->render($this->action->id, [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'cateMap' => Yii::$app->services->attachmentCate->getMap(),
        ]);
    }

    /**
     * @return mixed|string|\yii\web\Response
     * @throws \yii\base\ExitException
     */
    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');
        $model = $this->findModel($id);

        // ajax 校验
        $this->activeFormValidate($model);
        if ($model->load(Yii::$app->request->post())) {
            return $model->save()
                ? $this->redirect(['index'])
                : $this->message($this->getError($model), $this->redirect(['index']), 'error');
        }

        return $this->renderAjax($this->action->id, [
            'model' => $model,
            'cateMap' => Yii::$app->services->attachmentCate->getMap(),
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (
            empty($id) || empty(
                ($model = $this->modelClass::find()
                    ->where(['id' => $id])
                    ->andFilterWhere(['merchant_id' => $this->getMerchantId()])
                    ->one()))
        ) {
            $model = new $this->modelClass;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

backend/modules/common/views/attachment/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html as BaseHtml;
use common\helpers\Html;
use common\helpers\ImageHelper;
use common\helpers\DebrisHelper;
use common\helpers\Url;
use common\enums\AttachmentDriveEnum;
use common\enums\AttachmentUploadTypeEnum;

$this->title = '文件列表';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-12 col-sm-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="<?= Url::to(['attachment/index']) ?>"> 资源文件</a></li>
                <li><a href="<?= Url::to(['attachment-cate/index']) ?>"> 资源分类</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        // 重新定义分页样式
                        'tableOptions' => ['class' => 'table table-hover'],
                        'columns' => [
                            [
                                'class' => 'yii\grid\SerialColumn',
                            ],
                            [
                                'attribute' => 'url',
                                'filter' => false, //不显示搜索框
                                'value' => function ($model) {
                                    if (($model['upload_type'] == 'images' || preg_match("/^image/", $model['specific_type'])) && $model['extension'] != 'psd') {
                                        return ImageHelper::fancyBox($model->url);
                                    }

                                    return BaseHtml::a('预览', $model->url, [
                                        'target' => '_blank'
                                    ]);
                                },
                                'format' => 'raw'
                            ],
                            [
                                'attribute' => 'upload_type',
                                'headerOptions' => ['class' => 'col-md-1'],
                                'filter' => Html::activeDropDownList($searchModel, 'upload_type', AttachmentUploadTypeEnum::getMap(), [
                                        'prompt' => '全部',
                                        'class' => 'form-control'
                                    ]
                                ),
                                'value' => function ($model) {
                                    return AttachmentUploadTypeEnum::getValue($model->upload_type);
                                },
                            ],
                            [
                                'attribute' => 'drive',
                                'headerOptions' => ['class' => 'col-md-1'],
                                'filter' => Html::activeDropDownList($searchModel, 'drive', AttachmentDriveEnum::getMap(), [
                                        'prompt' => '全部',
                                        'class' => 'form-control'
                                    ]
                                ),
                                'value' => function ($model) {
                                    return AttachmentDriveEnum::getValue($model->drive);
                                },
                            ],
                            'name',
                            [
                                'attribute' => 'format_size',
                                'filter' => false, //不显示搜索框
                            ],
                            [
                                'attribute' => 'extension',
                                'headerOptions' => ['class' => 'col-md-1'],
                            ],
                            [
                                'attribute' => 'cate.title',
                                'label' => '分类',
                                'headerOptions' => ['class' => 'col-md-1'],
                                'filter' => Html::activeDropDownList($searchModel, 'cate_id', $cateMap, [
                                        'prompt' => '全部',
                                        'class' => 'form-control'
                                    ]
                                ),
                            ],
                            [
                                'label' => '位置信息',
                                'value' => function ($model) {
                                    $str = [];
                                    $str[] = DebrisHelper::analysisIp($model->ip);
                                    $str[] = $model->ip;
                                    return implode('</br>', $str);
                                },
                                'format' => 'raw',
                            ],
                            [
                                'label' => '创建时间',
                                'attribute' => 'created_at',
                                'filter' => false, //不显示搜索框
                                'format' => ['date', 'php:Y-m-d H:i:s'],
                            ],
                            [
                                'header' => "操作",
                                'class' => 'yii\grid\ActionColumn',
                                'template' => '{update} {status} {delete}',
                                'buttons' => [
                                    'update' => function ($url, $model, $key) {
                                        return Html::linkButton(['update', 'id' => $model->id], '编辑', [
                                                'data-toggle' => 'modal',
                                                'data-target' => '#ajaxModal',
                                            ]);
                                    },
                                    'status' => function ($url, $model, $key) {
                                        return Html::status($model->status);
                                    },
                                    'delete' => function ($url, $model, $key) {
                                        return Html::delete(['destroy', 'id' => $model->id]);
                                    },
                                ],
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>

backend/modules/common/views/attachment/update.php
<?php

use yii\widgets\ActiveForm;
use common\helpers\ArrayHelper;
use common\helpers\Url;

$form = ActiveForm::begin([
    'id' => $model->formName(),
    'enableAjaxValidation' => true,
    'validationUrl' => Url::to(['update', 'id' => $model['id']]),
]);
?>

    <div class="modal-header">
        <h4 class="modal-title">基本信息</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
    <div class="modal-body">
        <?= $form->field($model, 'name')->textInput(); ?>
        <?= $form->field($model, 'cate_id')->dropDownList($cateMap, [
            'prompt' => '请选择',
        ]); ?>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
        <button class="btn btn-primary" type="submit">保存</button>
    </div>
<?php ActiveForm::end(); ?>